# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourhorsemen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('most_used', models.TextField()),
            ],
        ),
    ]
