# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourhorsemen', '0002_socialfrequency_socialmost'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowAbusive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abusive', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HowAppropriate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appropriate', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HowHarassing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harassing', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HowOften',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('often', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HowSevere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WhichRemediation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remediation', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ExperimentalConditionMap',
        ),
        migrations.RemoveField(
            model_name='experimentquestion',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='surveyanswers',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userdemographic',
            name='demo_type',
        ),
        migrations.RemoveField(
            model_name='userdemographic',
            name='user',
        ),
        migrations.DeleteModel(
            name='DemoTypes',
        ),
        migrations.DeleteModel(
            name='ExperimentalConditions',
        ),
        migrations.DeleteModel(
            name='ExperimentQuestion',
        ),
        migrations.DeleteModel(
            name='SurveyAnswers',
        ),
        migrations.DeleteModel(
            name='SurveyQuestion',
        ),
        migrations.DeleteModel(
            name='UserDemographic',
        ),
    ]
