# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourhorsemen', '0003_auto_20170409_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputationalModeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HarassmentTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harassmenttype', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImportantPrevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevention', models.TextField()),
            ],
        ),
    ]
