# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourhorsemen', '0004_computationalmoderation_harassmenttypes_importantprevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='YesNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
    ]
