# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourhorsemen', '0005_yesno'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhichModerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderatorchoice', models.TextField()),
            ],
        ),
    ]
